export { __editable, useEditable } from './runtime'
export { JsonConfigProvider, JsonConfigContext, useJsonConfig, ConfigScope, useEditablePrefix } from './context'
export type { EditingTarget } from './context'
export { getValueByPath, setValueByPath } from './path'
export { default as InlineEditor } from './InlineEditor'
